name: Deploy to EC2

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/38-SOPKATHON-SERVER-WEB1
            git pull origin develop
            export DB_HOST="${{ secrets.DB_HOST }}"
            export DB_PORT="${{ secrets.DB_PORT }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_S3_BUCKET="${{ secrets.AWS_S3_BUCKET }}"
            export AWS_REGION="${{ secrets.AWS_REGION }}"
            chmod +x ./gradlew
            ./gradlew clean build -x test
            if [ -f app.pid ]; then
              kill $(cat app.pid) || true
              sleep 3
            fi
            nohup java -Dspring.profiles.active=prod -jar build/libs/sopkathon-server-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            echo $! > app.pid